### ISSUE TITLE
Completion text is too light

### ISSUE THREAD

**Issue by jef** [one-dark/iterm-one-dark-theme#5]
I updated all the "Bright" colors by 20 in RGB -- it helps a little. Still seems to be too dark for the history completion. (Without any change, the colors would blend into background.)

![image](https://user-images.githubusercontent.com/12074633/70080436-895c5080-15d4-11ea-83c7-50b4d17ecf2c.png)

Increasing RGB by 50 seems to be better:

![image](https://user-images.githubusercontent.com/12074633/70080521-b27ce100-15d4-11ea-91aa-a6b22d18ed18.png)

**Comment by mskelton** [comment]
@hijxf Thanks for opening this issue!  From what I recall when setting my shell up a while back, auto complete colors like this are actually part of ZSH, Fish, or whichever shell you are using.  Could you share a code snippet with the changes you made to the colors?

Thanks!

**Comment by jef** [comment]
Sure thing, I'll send in the morning.
